# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/passion/setup-makefiles.sh
PRODUCT_DEVICE := passion
PRODUCT_MODEL := Nexus One
PRODUCT_NAME := passion

PRODUCT_BUILD_PROP_OVERRIDES += PRODUCT_NAME=passion PRODUCT_MODEL="Nexus One" PRODUCT_BRAND=google BUILD_ID=GRI40 BUILD_DISPLAY_ID=GRI40 BUILD_FINGERPRINT=google/passion/passion:2.3.3/GRI40/102588:user/release-keys PRIVATE_BUILD_DESC="passion-user 2.3.3 GRI40 102588 release-keys"

PRODUCT_PROPERTY_OVERRIDES += \
    ro.url.legal=http://www.google.com/intl/%s/mobile/android/basic/phone-legal.html \
    ro.url.legal.android_privacy=http://www.google.com/intl/%s/mobile/android/basic/privacy.html \
    ro.com.google.clientidbase=android-google \
    ro.com.android.wifi-watchlist=GoogleGuest \
    ro.setupwizard.enterprise_mode=1 \
    ro.setupwizard.mode=OPTIONAL \
    ro.modversion=mnlk2_v0.1

# Live wallpaper packages
PRODUCT_PACKAGES := \
    LiveWallpapersPicker \
    MagicSmokeWallpapers \
    VisualizationWallpapers \
    librs_jni

# Publish that we support the live wallpaper feature.
PRODUCT_COPY_FILES := \
    packages/wallpapers/LivePicker/android.software.live_wallpaper.xml:/system/etc/permissions/android.software.live_wallpaper.xml
    
# Pick up overlay for features that depend on non-open-source files
PRODUCT_PACKAGE_OVERLAYS += vendor/htc/passion/overlay
    
#copy Gapps
ifdef WITH_GOOGLE
    PRODUCT_COPY_FILES += \
	vendor/htc/passion/gapps/CarHomeLauncher.apk:./system/app/CarHomeLauncher.apk \
	vendor/htc/passion/gapps/FOTAKill.apk:./system/app/FOTAKill.apk \
        vendor/htc/passion/gapps/GenieWidget.apk:./system/app/GenieWidget.apk \
        vendor/htc/passion/gapps/GoogleBackupTransport.apk:./system/app/GoogleBackupTransport.apk \
        vendor/htc/passion/gapps/GoogleCalendarSyncAdapter.apk:./system/app/GoogleCalendarSyncAdapter.apk \
        vendor/htc/passion/gapps/GoogleContactsSyncAdapter.apk:./system/app/GoogleContactsSyncAdapter.apk \
        vendor/htc/passion/gapps/GoogleFeedback.apk:./system/app/GoogleFeedback.apk \
        vendor/htc/passion/gapps/GooglePartnerSetup.apk:./system/app/GooglePartnerSetup.apk \
        vendor/htc/passion/gapps/GoogleQuickSearchBox.apk:./system/app/GoogleQuickSearchBox.apk \
        vendor/htc/passion/gapps/GoogleServicesFramework.apk:./system/app/GoogleServicesFramework.apk \
        vendor/htc/passion/gapps/LatinImeTutorial.apk:./system/app/LatinImeTutorial.apk \
	vendor/htc/passion/gapps/LiveWallpapers.apk:./system/app/LiveWallpapers.apk \
        vendor/htc/passion/gapps/MarketUpdater.apk:./system/app/MarketUpdater.apk \
        vendor/htc/passion/gapps/MediaUploader.apk:./system/app/MediaUploader.apk \
        vendor/htc/passion/gapps/NetworkLocation.apk:./system/app/NetworkLocation.apk \
        vendor/htc/passion/gapps/OneTimeInitializer.apk:./system/app/OneTimeInitializer.apk \
	vendor/htc/passion/gapps/SetupWizard.apk:./system/app/SetupWizard.apk \
        vendor/htc/passion/gapps/Talk.apk:./system/app/Talk.apk \
        vendor/htc/passion/gapps/Vending.apk:./system/app/Vending.apk \
        vendor/htc/passion/gapps/com.google.android.maps.xml:./system/etc/permissions/com.google.android.maps.xml \
        vendor/htc/passion/gapps/features.xml:./system/etc/permissions/features.xml \
        vendor/htc/passion/gapps/com.google.android.maps.jar:./system/framework/com.google.android.maps.jar \
	vendor/htc/passion/gapps/libvoicesearch.so:./system/lib/libvoicesearch.so \
	vendor/htc/passion/gapps/google_generic_update.txt:./system/etc/updatecmds/google_generic_update.txt
else 
    PRODUCT_COPY_FILES += \
	vendor/htc/passion/gapps/LiveWallpapers.apk:./system/app/LiveWallpapers.apk \
	vendor/htc/passion/gapps/google_generic_update.txt:./system/etc/updatecmds/google_generic_update.txt
endif
       

$(call inherit-product, vendor/htc/passion/device-vendor-blobs.mk)
