#!/system/bin/sh
#
LOG="log -p i -t IGot!Name"
$LOG " 
 _____   _____       _     _ _   _                      
|_   _| |  __ \     | |   | | \ | |                     
  | |   | |  \/ ___ | |_  | |  \| | __ _ _ __ ___   ___ 
  | |   | | __ / _ \| __| | | . \` |/ _\` | '_ \` _ \ / _ \\
 _| |_  | |_\ \ (_) | |_  |_| |\  | (_| | | | | | |  __/
 \___/   \____/\___/ \__| (_)_| \_/\__,_|_| |_| |_|\___|
"
# http://patorjk.com/software/taag/
# escape stuff like backquotes (`) and \ at end of lines with \
